name: easy_toast_plus
description: A lightweight Flutter toast package for showing simple toast messages anywhere in your app.
version: 1.0.2
repository: https://github.com/tyneaung-cto/easy_toast.git
homepage: https://github.com/tyneaung-cto/easy_toast

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.6

flutter:
  uses-material-design: true
